{{- if .Values.hpa.celery.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "agent-studio.fullname" . }}-celery
  labels:
    {{- include "agent-studio.labels" . | nindent 4 }}
    component: celery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "agent-studio.fullname" . }}-celery
  minReplicas: {{ .Values.hpa.celery.minReplicas }}
  maxReplicas: {{ .Values.hpa.celery.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.celery.targetCPUUtilizationPercentage }}
{{- end }}
