{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-studio.postgres.fullname" . }}
  labels:
    {{- include "agent-studio.labels" . | nindent 4 }}
    component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "agent-studio.selectorLabels" . | nindent 4 }}
    component: postgres
{{- end }}
