apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-studio.fullname" . }}-frontend
  labels:
    {{- include "agent-studio.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "agent-studio.selectorLabels" . | nindent 4 }}
    component: frontend
