{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-studio.redis.fullname" . }}
  labels:
    {{- include "agent-studio.labels" . | nindent 4 }}
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "agent-studio.selectorLabels" . | nindent 4 }}
    component: redis
{{- end }}
