apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-studio.backend.fullname" . }}
  labels:
    {{- include "agent-studio.labels" . | nindent 4 }}
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agent-studio.selectorLabels" . | nindent 4 }}
    component: backend
