"""Contextual Retrieval — Anthropic's technique for improving RAG accuracy.

Before embedding, each chunk is prepended with a short document-level context
summary generated by an LLM.  Anthropic's research shows this reduces
retrieval failures by 67% (5.17% → 1.67% irrelevant chunks).

The context prefix is embedded alongside the chunk text (better semantic
matching), but the original text is preserved in metadata for display and
LLM context injection.
"""

from __future__ import annotations

import os
from typing import Any

from core.infra.logging_config import get_logger

logger = get_logger(__name__)

# Context prefix target length — short enough to not dilute the chunk signal,
# long enough to ground the embedding in document-level semantics.
_CONTEXT_MAX_WORDS = int(os.environ.get("CONTEXTUAL_MAX_WORDS", "80"))

# LLM budget for context generation — one call per batch of chunks.
_CONTEXT_LLM_TIMEOUT = int(os.environ.get("CONTEXTUAL_LLM_TIMEOUT", "30"))


def build_context_prefix_prompt(
    document_text: str,
    chunks: list[str],
) -> str:
    """Build an LLM prompt that generates a context prefix for each chunk.

    The prompt asks for a concise document-level summary (1-2 sentences) that
    would help disambiguate the chunk if it appeared in isolation — e.g. which
    file, which topic, which section of the document.
    """
    # Truncate document to fit LLM context window — first 2000 chars usually
    # contains the title, TOC, and key sections.
    truncated_doc = document_text[:2000]
    if len(document_text) > 2000:
        truncated_doc += "\n...[truncated]..."

    # Batch chunks to reduce LLM calls — ask for one context per chunk.
    numbered_chunks = "\n".join(
        f"[{i}] {c[:200]}{'...' if len(c) > 200 else ''}"
        for i, c in enumerate(chunks)
    )

    return (
        f"You are generating document-level context prefixes for RAG retrieval.\n\n"
        f"DOCUMENT (first 2000 chars):\n```\n{truncated_doc}\n```\n\n"
        f"CHUNKS TO CONTEXTUALIZE:\n{numbered_chunks}\n\n"
        f"Task: For each chunk, write a 1-sentence context prefix that would "
        f"help someone understand where this chunk comes from in the document. "
        f"Include the document title/subject and section topic. "
        f"Max {_CONTEXT_MAX_WORDS} words per prefix.\n\n"
        f"Respond ONLY with a JSON array of strings, one per chunk, "
        f"in the same order. No explanation.\n"
        f'Example: ["This document is about X. This chunk covers Y.", ...]'
    )


def parse_context_response(
    response_text: str, expected_count: int
) -> list[str]:
    """Parse LLM response into a list of context prefixes.

    Handles JSON array responses and falls back to line-by-line parsing
    if JSON decoding fails.
    """
    import json

    text = response_text.strip()
    # Strip markdown code fences if present
    if text.startswith("```"):
        lines = text.split("\n")
        text = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

    try:
        parsed = json.loads(text)
        if isinstance(parsed, list):
            # Truncate each prefix to max words
            result = []
            for p in parsed[:expected_count]:
                words = str(p).split()
                if len(words) > _CONTEXT_MAX_WORDS:
                    p = " ".join(words[:_CONTEXT_MAX_WORDS])
                result.append(p)
            # Pad with empty strings if LLM returned fewer than expected
            while len(result) < expected_count:
                result.append("")
            return result
    except (json.JSONDecodeError, TypeError):
        logger.warning("Context response not valid JSON, falling back to line split")

    # Fallback: split by newline
    lines = [ln.strip().strip('"').strip("'") for ln in text.split("\n") if ln.strip()]
    result = []
    for line in lines[:expected_count]:
        words = line.split()
        if len(words) > _CONTEXT_MAX_WORDS:
            line = " ".join(words[:_CONTEXT_MAX_WORDS])
        result.append(line)
    while len(result) < expected_count:
        result.append("")
    return result


async def generate_context_prefixes(
    document_text: str,
    chunk_texts: list[str],
    api_key: str,
    model: str | None = None,
    base_url: str | None = None,
) -> list[str]:
    """Generate document-level context prefixes for a batch of chunks.

    Uses the same LLM provider as the RAG generation pipeline.
    Returns one prefix per chunk — empty string on failure (graceful degradation).
    """
    if not chunk_texts:
        return []

    if not api_key:
        logger.warning("Contextual retrieval skipped: no API key")
        return [""] * len(chunk_texts)

    prompt = build_context_prefix_prompt(document_text, chunk_texts)

    try:
        import json
        import urllib.request

        # Use OpenAI-compatible chat completions API
        provider_model = model or "deepseek-ai/DeepSeek-V3"
        url = (base_url or "https://api.siliconflow.cn/v1") + "/chat/completions"

        body = {
            "model": provider_model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.3,
            "max_tokens": 2000,
        }

        payload = json.dumps(body).encode("utf-8")
        req = urllib.request.Request(url, data=payload, method="POST")
        req.add_header("Authorization", f"Bearer {api_key}")
        req.add_header("Content-Type", "application/json")

        with urllib.request.urlopen(req, timeout=_CONTEXT_LLM_TIMEOUT) as resp:
            result = json.loads(resp.read().decode("utf-8"))

        response_text = result["choices"][0]["message"]["content"]
        return parse_context_response(response_text, len(chunk_texts))

    except Exception:
        logger.exception("Contextual retrieval: LLM call failed — falling back to no context")
        return [""] * len(chunk_texts)


def apply_context_prefixes(
    chunks: list[Any],
    prefixes: list[str],
) -> None:
    """Apply context prefixes to chunks.

    - Prepends prefix to chunk.text for embedding (vector space).
    - Stores original text in chunk.metadata["original_text"] for display.
    - Stores prefix in chunk.metadata["context_prefix"] for transparency.
    """
    for chunk, prefix in zip(chunks, prefixes, strict=True):
        if not prefix:
            continue
        # Preserve original text for display and LLM context
        chunk.metadata["original_text"] = chunk.text
        chunk.metadata["context_prefix"] = prefix
        # Prepend context for embedding — this is what the vector captures
        chunk.text = f"{prefix}\n\n{chunk.text}"
