"""add workflow config tables

Revision ID: 8347788032e5
Revises: 2b69c6f32e6a
Create Date: 2026-07-10 17:52:11.470248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8347788032e5'
down_revision: Union[str, Sequence[str], None] = '2b69c6f32e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(name: str) -> bool:
    """Check if a table exists in the current database."""
    conn = op.get_bind()
    inspector = __import__("sqlalchemy").inspect(conn)
    return name in inspector.get_table_names()


def _index_exists(name: str) -> bool:
    """Check if an index exists in the current database."""
    conn = op.get_bind()
    inspector = __import__("sqlalchemy").inspect(conn)
    for table_name in inspector.get_table_names():
        for idx in inspector.get_indexes(table_name):
            if idx["name"] == name:
                return True
    return False


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_configs_team_id'), 'workflow_configs', ['team_id'], unique=True)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_config_id', sa.String(length=36), nullable=False),
    sa.Column('agent_config_id', sa.String(length=36), nullable=False),
    sa.Column('role_identifier', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_config_id'], ['workflow_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_nodes_workflow_config_id'), 'workflow_nodes', ['workflow_config_id'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_config_id', sa.String(length=36), nullable=False),
    sa.Column('from_node_id', sa.String(length=36), nullable=False),
    sa.Column('to_node_id', sa.String(length=36), nullable=False),
    sa.Column('condition_key', sa.String(length=128), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_config_id'], ['workflow_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_edges_workflow_config_id'), 'workflow_edges', ['workflow_config_id'], unique=False)

    # Drop old LangGraph runtime tables if they exist (created at runtime, not by migrations)
    if _table_exists('checkpoint_writes'):
        if _index_exists('checkpoint_writes_thread_id_idx'):
            op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
        op.drop_table('checkpoint_writes')
    if _table_exists('agent_checkpoints'):
        if _index_exists('ix_checkpoints_session_id'):
            op.drop_index(op.f('ix_checkpoints_session_id'), table_name='agent_checkpoints')
        op.drop_table('agent_checkpoints')
    if _table_exists('checkpoint_blobs'):
        if _index_exists('checkpoint_blobs_thread_id_idx'):
            op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
        op.drop_table('checkpoint_blobs')
    if _table_exists('checkpoints'):
        if _index_exists('checkpoints_thread_id_idx'):
            op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
        op.drop_table('checkpoints')
    if _table_exists('checkpoint_migrations'):
        op.drop_table('checkpoint_migrations')
    op.drop_column('registered_skills', 'description')
    op.drop_column('registered_skills', 'owner_id')
    op.add_column('teams', sa.Column('workflow_config_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'teams', 'workflow_configs', ['workflow_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'workflow_config_id')
    op.add_column('registered_skills', sa.Column('owner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('registered_skills', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey1'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('agent_checkpoints',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('step_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_state', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['project_runs.id'], name=op.f('checkpoints_run_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('checkpoints_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('ix_checkpoints_session_id'), 'agent_checkpoints', ['session_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_workflow_edges_workflow_config_id'), table_name='workflow_edges')
    op.drop_table('workflow_edges')
    op.drop_index(op.f('ix_workflow_nodes_workflow_config_id'), table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index(op.f('ix_workflow_configs_team_id'), table_name='workflow_configs')
    op.drop_table('workflow_configs')
    # ### end Alembic commands ###
